# Site settings
title: Darbadar
email: harsha.chaudhary@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writer | Travel Photographer | Storyteller 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://darbadar-dev.netlify.com"
permalink: /:categories/:year/:month/:title/
timezone: Asia/Kolkata
imageurl: https://farm1.staticflickr.com
imagesize: c
imageext: jpg

# Build settings
markdown: kramdown
