# Site settings
title: Darbadar
email: harsha.chaudhary@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Travel Blog 123
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://harshac.github.io/darbadar" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  harshac
permalink: /:year/:month/:title

# Build settings
markdown: kramdown
