# Site settings
title: Darbadar
email: harsha.chaudhary@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Travel Blog 123
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
permalink: /stories/:title
timezone: Asia/Kolkata

# Build settings
markdown: kramdown
